services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    container_name: greengoodies_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: greengoodies
      MYSQL_USER: greengoodies
      MYSQL_PASSWORD: greengoodies
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 5s
      retries: 10
      start_period: 120s
    volumes:
      - database_data:/var/lib/mysql:rw
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
